version: "3.8"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
  client:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "4300:80"
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - api
      - client
